name: Java Build and Store Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java code
      run: javac SimpleCalculator.java

    - name: Upload compiled class as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-java-class
        path: SimpleCalculator.class
